# Numpy

In this notebook we will see basics functions of the numpy package:

For that, you need to have the numpy package installed within your environment.

To install numpy, activate your environment and run the command: `conda install numpy`

In [51]:
import numpy as np

In [52]:
a = np.arange(8,32)
a

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31])

In [53]:
A = a.reshape(4,6)
print(A)

[[ 8  9 10 11 12 13]
 [14 15 16 17 18 19]
 [20 21 22 23 24 25]
 [26 27 28 29 30 31]]


### Boolean array

In [54]:
# create a boolean matrix B with True if the element of A and less than 15 (without using a loop)
B = A>15
B 

array([[False, False, False, False, False, False],
       [False, False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

### Axis reduction: sum

In [55]:
print(A.sum(axis=0))
print(A.sum(axis=1))

[68 72 76 80 84 88]
[ 63  99 135 171]


### Slicing on NumPy arrays

In [56]:
print(A)

# this operation is called slicing:
AA = A[:,1::2] # All columns from column 1, skipping every 2-1=1 columns
print(AA)

AA = A[0::3,:] # All lines from line 0, skipping every 3-1=2 lines
print(AA)

[[ 8  9 10 11 12 13]
 [14 15 16 17 18 19]
 [20 21 22 23 24 25]
 [26 27 28 29 30 31]]
[[ 9 11 13]
 [15 17 19]
 [21 23 25]
 [27 29 31]]
[[ 8  9 10 11 12 13]
 [26 27 28 29 30 31]]


### Matrix dot product

Compute $$ E = A A^T $$

In [57]:
At = np.transpose(A)
AAt = np.dot(A,At)
print(AAt)

[[ 679 1057 1435 1813]
 [1057 1651 2245 2839]
 [1435 2245 3055 3865]
 [1813 2839 3865 4891]]


### 3-D array

Array F is a 3D array: 2 matrices with 4 rows and 3 columns each

In [58]:
F = A.reshape(2,4,3)
print(F)

[[[ 8  9 10]
  [11 12 13]
  [14 15 16]
  [17 18 19]]

 [[20 21 22]
  [23 24 25]
  [26 27 28]
  [29 30 31]]]


In [59]:
# print the number of dimensions of F
np.shape(F)

(2, 4, 3)

In [60]:
v = np.array([1,2,3,4])
print(a)

[ 8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]
